[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 266, lines = 66 }

[font]
size = 12.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'
bright_foreground = '#d5bd86'

# Normal colors
[colors.normal]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

# Bright colors
[colors.bright]
black = '#a7afa1'
red = '#e56058'
green = '#90a030'
yellow = '#d5a236'
blue = '#5392c0'
magenta = '#d06fb6'
cyan = '#58a47e'
white = '#eeebde'

